version: '3.1'
services:
  db:
    image: postgres
    container_name: db_collab
    environment:
      POSTGRES_USER: collab_user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: collab
    ports:
      - "5432:5432"
    volumes:
      - db_collab_data:/var/lib/postgresql

volumes:
  db_collab_data: